### ISSUE TITLE
mptcp to different ports

### ISSUE THREAD

**Issue by debiansid** [multipath-tcp/mptcp#135]
I want to make mptcp working like this:
Server(with MPTCP):port1--->VPS1
                                  port2--->VPS2
mptcp can choose faster link automatically.

**Comment by cpaasch** [comment]
What does "VPS" mean here?

**Comment by GinesGarcia** [comment]
Hi,
do you want to use just the faster link?if so, mptcp was created to send data through multiples paths (not to select the best link and send data through), but mptcp is able to send more data through the less congested link (balance congestion), so probably, you can use it.

**Comment by debiansid** [comment]
vps means server running shadowsocks server

**Comment by debiansid** [comment]
I cannot find configuration related to port

**Comment by cpaasch** [comment]
With "port" you mean interface, right?

**Comment by debiansid** [comment]
TCP port like 8001 8002, not interface

**Comment by GinesGarcia** [comment]
mptcp with ndiffports associates a "random" source port with a subflow (in a high level of view), but you can't associate a concrete port to a MPTCP subflow. For example:
 - server1  -->mptcp connection --> server2
   * mptcp configured with ndiffports
   * mptcp configured with two subflows
   * server1 has one interface
   * Threre are two links between server1 and server2 (provided by their edge routers)
with this configuration you can send one subflow to server2 using link1 and the other subflow using link2. In this case you need an "extra" software in order to perform subflow redirection through the different links.

**Comment by GinesGarcia** [comment]
You can use ndiffports in order to generate more than one subflow per interface. Each subflow, that belongs to the same mptcp connection, has a different source port but you can't assign arbitrary source ports (this is a mptcp kernel job).

**Comment by cpaasch** [comment]
Closing, as the question has been answered.
