### ISSUE TITLE
Can't use multiple subflows v0.93.0

### ISSUE THREAD

**Issue by robl-25** [multipath-tcp/mptcp#228]
Hi there.

The problem I have is that MPTCP creates multiple subflows but only one of them
is actually used.

## Setup
I am using two HPE ProLiant ML30 Gen9 hosts installed with latest Ubuntu 16.04
with kernel compiled by me as described [here](http://multipath-tcp.org/pmwiki.php/Users/DoItYourself).
More precisely I executed the following:
```shell
make
sudo make modules_install
sudo make install
```
So I am running Linux 4.9.60 with MPTCP v0.93.0.

## Logs
I did
```shell
sudo sysctl -w net.mptcp.mptcp_debug=1
```

which gave me the following logs: [log_mptcp.txt](https://github.com/multipath-tcp/mptcp/files/1463171/log_mptcp.txt)

**Comment by cpaasch** [comment]
What kind of traffic are you sending? And are you sure that you are filling the link of the initial subflow?

**Comment by robl-25** [comment]
Thanks for the quick response @cpaasch.

I was testing my setup simply sending the output of `yes` from one machine to
the other using `nc`.
More precisely I was using on the server side
```shell
nc -l 4000 > /dev/null
```
and on the client side
```shell
yes | nc SERVER 4000
```
I was able to verify that multiple subflows were actually used. The two machines
I am using to test are connected to each other by five different interfaces and,
once I inspected the traffic with wireshark, I saw packages marked as MPTCP being
sent to multiple destination addresses (all of them belonging to the right host).

However when I try to check if MPTCP was set up properly (as described
[here](http://blog.multipath-tcp.org/blog/html/2015/12/16/mptcp_tools.html)) it still reports that I am not using it:
```shell
curl http://www.multipath-tcp.org
```
reports
```
Nay, Nay, Nay, your have an old computer that does not speak MPTCP. Shame on you!
```

**Comment by Gangadhar-Akula** [comment]
The reason for this is, the path to MPTCP web server is not supporting MPTCP.
I do come across this problem. I have tested MPTCP using the server that I have setup on AWS server using multiple interfaces. I can see that multiple subflows created and data transmitted across multiple channels.

But when I use the following command
curl http://www.multipath-tcp.org
I received this message.
Nay, Nay, Nay, your have an old computer that does not speak MPTCP. Shame on you!
It doe simply means, the path to the destination is not supporting MPTCP.

Use 
curl --interface ethX http://www.multipath-tcp.org
If you look at tcpdump using tcpdump -eni ethX |grep mptcp
You will notice an MPTCP packet sent to the destination but there is no further MPTCP communication on the interface because of one of the following reasons.
1.The MPTCP server does not receive MP_CAPABLE options on forward path due to middlebox.
2.On the reverse path, some middlebox might have stripped MPTCP options on SYN/ACK sent by MPTCP server.
