### ISSUE TITLE
Verifying MPTCP at transport layer

### ISSUE THREAD

**Issue by sukkhi** [multipath-tcp/mptcp#230]
Hi,
I am using **vodafone 4G USB Dongle** for internet connection.
I opened **http://amiusingmptcp.de/** on the web browser.

It showed ```No MPTCP```  for ports 80(http), 5900(vnc), 8080(http-alt) respectively. 
Also I checked from wireshark logs  that ```SYN``` was added with "**option 30**" ie ```MPTCP capable```
for all the ports(80, 8080, 5900), but in ```SYN_ACK```  "**option 30**" was not included.

May be Middleboxes would have blocked MPTCP option for above specified ports.
```curl http://www.multipath-tcp.org``` didn't worked too.

QUERY: So I just need to know that, is there any other way to check  ```MPTCP (option 30)``` on other tcp ports.

Also I tried same scenario with dsl, & observed that MPTCP capable ```SYN_ACK``` was received for ports 5900 & 8080 respectively.

**Comment by matttbe** [comment]
Hi @sukkhi,

Indeed, some operators have a PEP to accelerate some kind of connections (like HTTP ones). Please report this error to your operator, their PEP is clearly not transparent. Better if they are aware that MPTCP is used in their network.

To check if MPTCP is "blocked", you can use Tracebox: http://tracebox.org/

```bash
sudo tracebox -np 'IP/tcp{dst=80}/MPCAPABLE' amiusingmptcp.de
tracebox to 18.194.8.156 (amiusingmptcp.de): 64 hops max
1: *
2: 81.246.124.193  [PARTIAL] IP::TTL IP::CheckSum 
3: *
4: 91.183.246.71  [PARTIAL] IP::TTL IP::CheckSum 
5: 91.183.246.70  [PARTIAL] IP::TTL IP::CheckSum 
6: 91.183.246.104  [PARTIAL] IP::TTL IP::CheckSum 
7: *
8: *
9: 94.102.162.35  [PARTIAL] IP::TTL IP::CheckSum 
10: 195.66.225.175  [PARTIAL] IP::TTL IP::CheckSum 
11: 54.239.100.8 IP::TTL IP::CheckSum 
12: 54.239.100.25 IP::TTL IP::CheckSum 
13: 54.239.42.139 IP::TTL IP::CheckSum 
14: 54.239.106.128 IP::TTL IP::CheckSum 
15: 54.239.106.121  [PARTIAL] IP::TTL IP::CheckSum 
16: *
17: *
18: 54.239.4.216  [PARTIAL] IP::TTL IP::CheckSum 
19: 18.194.8.156 TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags TCP::WindowsSize TCP::CheckSum IP::TotalLength IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP +TCPOptionMaxSegSize TCPOptionMPTCPCapable::Sender's Key
```

Here, you can see that I have many "PARTIAL": we cannot know if they have stripped MPTCP options. But the HOP 11 has only changed the TTL and CheckSum (normal, no middlebox from 0 to 11). When we arrive at the server side, it supports MPTCP on this port because it has returned a SYN+ACK with MPTCP options. 

You can change the port 80 but of course the remote server need to listen on this port if you want to have a valid last line.
