### ISSUE TITLE
Congestion control="lia"

### ISSUE THREAD

**Issue by Dimitris85** [multipath-tcp/mptcp#258]
Hello MPTCP community,

my name is Dimitris Makris and i am using the MPTCP kernel release 4.14.24.mptcp. (http://multipath-tcp.org/pmwiki.php/Users/AptRepository)
I try to insert congestion control "lia" module, but the output is:
sudo insmod /lib/modules/4.12.24.mptcp/kernel/net/mptcp_olia.ko
insmod: ERROR: could not insert module
/lib/modules/4.12.24.mptcp/kernel/net/mptcp_olia.ko: Invalid paerameters
Should i change the kernel version of mptcp?

Thank you very much.

Best Regards,
Dimitris

**Comment by matttbe** [comment]
Hi @Dimitris85 

This bug, similar to #254, has already been fixed in https://github.com/multipath-tcp/mptcp/commit/c2119e001dd45a4fa3cf2c33d513e84662dd030e

If you want the fix sooner, please compile MPTCP by using the sources from Github (the branch mptcp_v0.94 should be the default one) : http://multipath-tcp.org/pmwiki.php/Users/DoItYourself

Cheers,
Matt

**Comment by psfabio** [comment]
Hi,
Is this error already fixed on apt repository?

Thanks a lot.
Fabio

**Comment by cpaasch** [comment]
No, new packages haven’t been generated. I will do this within the next week.

**Comment by psfabio** [comment]
thanks a lot Christoph...
