### ISSUE TITLE
Code mentioned on the blog "Fixing problems before the submission deadline"

### ISSUE THREAD

**Issue by lenormf** [multipath-tcp/mptcp#304]
Hi,

I read the [article about Wifi/3G](http://blog.multipath-tcp.org/blog/html/2018/12/13/fixing_problems_before_the_submission_deadline.html), and the following bit caught my attention:

>First, when Multipath TCP detects that it is window-blocked and there is some unacknowledged data, it tries to re-inject the data over another subflow whose congestion window is open. If this data is acknowledged quickly, then the receiver will advertise a large receive window that will enable the sender to transmit. Unfortunately, this is not sufficient as the same situation could happen again later. The second part of the solution is to penalise the slow subflow by halving its congestion window.

I'm curious to know precisely which commits implement this two-prong solution, but I couldn't find them in the current codebase.

Could you please tell me which commits implement this solution?

Thanks.

**Comment by matttbe** [comment]
Hi,

According to the article, it is linked to the submission for NSDI12

> This result was annoying and we were less than a week before the submission deadline.

The submission deadline is visible there: https://www.usenix.org/legacy/events/nsdi/cfp/index.html

> Complete paper submissions due: October 4, 2011, 5:00 p.m. PDT (hard deadline)

Thanks to git, you can easily list commits created around this date:

    git log --before="Tue Oct 4 23:59:59 2011" --date-order mptcp_trunk -- net/ipv4

I guess it was not fixed in one commit but 10339ae96788c7c8c5fc1eada959b1755113d08f seems to be a good candidate for the penalisation part. I guess you can look at the history from there.

**Comment by lenormf** [comment]
Thanks, I didn't expect the articles to discuss features that old.
