### ISSUE TITLE
Ubuntu Server 18.04 long boot time

### ISSUE THREAD

**Issue by FiratA** [multipath-tcp/mptcp#310]
i have a picture of systemd-analyze critical-chain

hope you guys can help me.

thanks in advance
![img_2094](https://user-images.githubusercontent.com/42636135/51737231-61cf5a00-208c-11e9-8eb3-efcb496c8c50.JPG)

**Comment by matttbe** [comment]
Hi @FiratA ,

I am not sure to see the link with MPTCP. I don't even know if you are using mptcp kernel :)

It seems to be a known issue: https://forum.snapcraft.io/t/snapd-service-delays-startup-in-ubuntu-18-04-with-4-15-0-24/6205

I am going to close this issue if you don't mind. If a kernel config has to be changed, please tell us but it looks like it is due to something else ;-)

**Comment by FiratA** [comment]
thank you @matttbe, this helped me to solve the issue :)
