### ISSUE TITLE
Implement a path manager that prioritizes one interface to perform the MPTCP handshake

### ISSUE THREAD

**Issue by lenormf** [multipath-tcp/mptcp#322]
Hi,

Upon reading https://www.tessares.net/july-2017/ I noticed the below figure:

![](https://www.tessares.net/wp-content/uploads/2017/07/image4.png)

As we can see, the handshake is being described in global terms, and is not specific to any given interface (e.g. the Ethernet line, in a dual Ethernet/Wifi setup). Is it currently possible to easily force the MPTCP handshake to be performed over an interface of the user's choosing?

If not, would that be a feature the maintainers of this project would consider for implementation? It would be really useful in the field to reliably know which line would be used purely for protocol purposes (at first, until data can be sent on it), and which one would only received data.

Thanks!

**Comment by matttbe** [comment]
Hi Frank,

I am not sure to understand your questions.

> Is it currently possible to easily force the MPTCP handshake to be performed over an interface of the user's choosing?

The interface which will send the MP_CAPABLE is selected using the routing tables. Like any packet you send. If the default route is via the fixed line, you SYN+MP_CAPABLE will most probably go via the fixed line.
You can also set specific routes, add ip rules, etc. but that's not directly linked to MPTCP but to the IP layer.

**Comment by knxhm** [comment]
From my pov the interface which is used for initial handshake depends only on global route selection.
Franz
Am 07.03.19, 12:35, Frank LENORMAND <notifications@github.com> schrieb:
Hi,
Upon reading https://www.tessares.net/july-2017/ I noticed the below figure:

As we can see, the handshake is being described in global terms, and is not specific to any given interface (e.g. the Ethernet line, in a dual Ethernet/Wifi setup). Is it currently possible to easily force the MPTCP handshake to be performed over an interface of the user's choosing?
If not, would that be a feature the maintainers of this project would consider for implementation? It would be really useful in the field to reliably know which line would be used purely for protocol purposes (at first, until data can be sent on it), and which one would only received data.
Thanks!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/multipath-tcp/mptcp","title":"multipath-tcp/mptcp","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/multipath-tcp/mptcp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Implement a path manager that prioritizes one interface to perform the MPTCP handshake (#322)"}],"action":{"name":"View Issue","url":"https://github.com/multipath-tcp/mptcp/issues/322"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/multipath-tcp/mptcp/issues/322",
"url": "https://github.com/multipath-tcp/mptcp/issues/322",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lenormf** [comment]
Thanks for the reploies, I must have missed something, closing for now.
