### ISSUE TITLE
Scheduler BLEST: not working

### ISSUE THREAD

**Issue by Tycale** [multipath-tcp/mptcp#330]
Hello,

I am very interested in the BLEST (Blocking Estimation-based MPTCP) Scheduler. However, I was not able to have it working properly on my setup. I used two machines with the upstream mptcp kernel 4.19. mptcp "0.95" with two links. The MPTCP connections are correctly established but the sender is not pushing any data.

My setup works when the scheduler is set to "default". Am I missing something in order to be able to use this scheduler ?

@s6dlwebe I saw that you made this PR, do you have any idea of what is going on ?

Best Regards,
Thibault

PS: I can upload .pcap traces if needed.

**Comment by dweb32** [comment]
Hi @Tycale,

I remember having similar issues where the connection just stalled. But this only occurred in some previous versions of 0.94 before I applied some refactoring of the original BLEST code.

Can you share some information about the link properties? How do the latency and bandwidth relate to each other? In the case of very heterogeneous path combination, it is expected that the BLEST scheduler ignores the expensive/slow paths.

Just for testing, can you try the redundant or round-robin schedulers? 

P.S.: I don't have access to my computer lab at the moment, because I am on vacation now. I gonna try to reproduce it next week with 0.95 (did't test this release yet) when I am back in my office.

**Comment by Tycale** [comment]
Hello @s6dlwebe,

Good news, I just managed to have BLEST working !

I had a subflow that was explicitly marked as "backup" on my setup, and I didn't notice it ! Changing it to "on" resolved the issue. Of course, I was starting the connection on the IP of this backup link.. Thus, ending with this strange behavior ! Sorry for disturbing during your vacation.

I'll mark this as resolved, thanks a lot for BLEST !

Best regards
