### ISSUE TITLE
mptcp(0.87) not working in ubuntu

### ISSUE THREAD

**Issue by leidemon** [multipath-tcp/mptcp#371]
I have down the 0.87 code and complier it in ubuntu; I can see the MPTCP version in my ubuntu
root@lwd-virtual-machine:/home/lwd# dmesg | grep MPTCP
[    6.144297] MPTCP: Stable release v0.87.4

then I use it to test web (http://amiusingmptcp.de/),and it show NO mptcp;
and I dump the data, it show the my ubuntu send the syn (mptcp capable),but the test web does not send (mptcp capable), and I also use curl to test, it shows "Nay, Nay, Nay, your have an old computer that does not speak MPTCP. Shame on you!"

So there is a problem with the MPTCP installation in my environment?

**Comment by leidemon** [comment]
the link of screenshots capture :
https://pan.baidu.com/s/1Ohjem5QuiOxiqt7Cltwf1A

**Comment by matttbe** [comment]
Hi,

MPTCP v0.87 is no longer supported for a while and very old. I would not be able to tell you if it is due to the version you use or a middlebox on the way that drop MPTCP options.

Please install a supported version (v0.94/v0.95), check that it is working by having a client and server in your local network and then check if there is no middleboxes on the way stripping TCP options, e.g. using Tracebox.

I am going to close this ticket as we cannot help more with your current setup. Please re-open it or open a new ticket if you find issue with a supported version and if it is not due to the network.

**Comment by leidemon** [comment]
> MPTCP v0.87 is no longer supported for a while and very old. I would not be able to tell you if it is due to the version you use or a middlebox on the way that drop MPTCP options.
> 
> Please install a supported version (v0.94/v0.95), check that it is working by having a client and server in your local network and then check if there is no middleboxes on the way stripping TCP options, e.g. using Tracebox.

ok，thank you, I will try the lastest version.
