### ISSUE TITLE
Weird Default Scheduler behavior in Mininet

### ISSUE THREAD

**Issue by mdhuynh** [multipath-tcp/mptcp#446]
When I set up a simple experiment in Mininet with two hosts (client with two interfaces and server) and 4 switches and configure routing manually for MPTCP. However, the default scheduler is sending packets into two paths when I use iperf. Is it normal? Also, default value of fullmesh creates 4 subflows, is it divided 2 for each interface. And when fullmesh == 2, the number of subflows is 8 and server has 4 subflows. Is this normal? 
Thank you very much!

**Comment by matttbe** [comment]
> However, the default scheduler is sending packets into two paths when I use iperf. Is it normal?

Yes, the default scheduler is sending packets over multiple paths if any and if required: in short, it sends data to the subflow with the lowest estimated RTT first. If there is "no more room" to send data on this path, the next subflow is used, etc.

> Also, default value of fullmesh creates 4 subflows, is it divided 2 for each interface.

It creates 4 paths because both the client and the server have 2 "public" IPs. So with a "full-mesh" method, it will create 2*2 subflows.

> And when fullmesh == 2, the number of subflows is 8 and server has 4 subflows. Is this normal?

Which "2" are you talking about? With fullmesh, it will create all possible paths. If you have v4 and v6 on each interface in your setup, you will have 2*2 (v4) + 2*2 (v6) subflows.

Does it answer your questions? Can we close this ticket?

**Comment by mdhuynh** [comment]
Thank you for your kind reply! I still have some questions regarding LowRTT and FullMesh:

- So I understand the LowRTT only sends to one path at any given time with the lowest RTT, and it switches if the cwnd is filled in one subflow. I have a mininet with two paths, first path with 40 RTT and second path with 80 RTT (attached code in the zip file). However, whenever the second interface is joined with the MPTCP session (attached wireshark pcap in zip file), why two paths continuous sending (like redundant scheduler theory)

- I understand that fullmesh creates 2 subflows for each interface by default. I didn't know that one interface can have multiple subflows, how does this work? Does each interface gets two subflows or four subflows are used interchangeably between interface. And by wireshark, I can see that it creates 4 subflows immediate even when interface 2 IP is not advertised yet. 

Thank you
[mptcp.zip](https://github.com/multipath-tcp/mptcp/files/7306749/mptcp.zip)
!

**Comment by matttbe** [comment]
> So I understand the LowRTT only sends to one path at any given time with the lowest RTT, and it switches if the cwnd is filled in one subflow. I have a mininet with two paths, first path with 40 RTT and second path with 80 RTT (attached code in the zip file). However, whenever the second interface is joined with the MPTCP session (attached wireshark pcap in zip file), why two paths continuous sending (like redundant scheduler theory)

If your app sends a bunch of data -- like iPerf does -- the cwnd of the path with the lowest RTT will quickly be full. Then the second subflow's cwnd will be filled up, etc. At the end, both cwnd will grow to a certain point and, depending on the configured buffers, both subflows will be used "at the same time". MPTCP packets scheduler will queue packets on both subflows.

> I understand that fullmesh creates 2 subflows for each interface by default.

Not necessary: the client creates a mesh by using all usable IP it has to all advertised IP of the server. In other words, in your setup with both the client having 2 IPs, A and B, if you set the Fullmesh PM on the server, it will advised its second IP in your setup. On the client side, the PM will try to create 4 subflows: AA, AB, BA, BB. In your case, I guess there is no route to get all combinations so only AA and BB are created.

> And by wireshark, I can see that it creates 4 subflows immediate even when interface 2 IP is not advertised yet.

I only see 2 TCP streams: 2 SYN and 2 SYN+ACK.
I can also see some ICMP messages, I guess because some routes are not possible (AB/BA).

**Comment by mdhuynh** [comment]
This helps explain a lot. Thank you very much! I appreciate your time.
