### ISSUE TITLE
TCP_CORK output time is not respected

### ISSUE THREAD

**Issue by redward** [multipath-tcp/mptcp#47]
When the tcp_cork option is set, there is a 200 millisecond ceiling on the time for which output is corked by TCP_CORK. With mptcp the time is a little more than 400 ms.

Issue found with Packetdrill_Mptcp using 

[packetdrill_mptcp/gtests/net/packetdrill/examples/tests/tcp_headers/tcp_cork_on_01.pkt](https://github.com/ArnaudSchils/packetdrill_mptcp/blob/master/gtests/net/packetdrill/examples/tests/tcp_headers/tcp_cork_on_01.pkt)

Other time issue is directly documented in tcp_cork_on_03.pkt file test from the same folder

**Comment by cpaasch** [comment]
It's a minimum of 200 ms that the stack should wait (actually it's 1 RTO).
"Problem" is in tcp_check_probe_timer, we take the meta-rto, which is twice the highest RTO among all subflows. That's why mptcp waits 400ms.

The cork specification (man 7 tcp) is actually not consistent with what is implemented. It says that there should be a 200ms ceiling for the queued data to wait. But that's not the way the TCP stack implements it. The stack takes the RTO (which can be more than 200ms).

So, the question is whether there is a specific reason why the legacy TCP stack takes the RTO instead of just using a 200ms ceiling. If taking the RTO is the correct approach and not take the 200ms ceiling, then I would say that MPTCP is implementing it correctly. If the 200ms ceiling approach is rather the correct one, then we should fix legacy TCP too.

**Comment by redward** [comment]
All right. 
I understand the issue but could you explain : if you make 2 write call systems, for the same subflow ( as in  tcp_cork_on_01.pkt) the time to wait is then 600ms instead of 400ms (example in tcp_cork_on_03.pkt). 
Is this as expected ?

**Comment by cpaasch** [comment]
That's because in tcp_cork_on_03.pkt the ack comes back after 100ms. TCP sets the inital RTO after a first RTT-estimation (thanks to the third ack) to 3*RTT. So, 300ms.

As MPTCP takes 2*RTO, it waits for 600ms. Just send back the third ack not after 100ms but for example after 10ms.

**Comment by cpaasch** [comment]
Seems like upstream Linux also does not handle it correctly for regular TCP. Thus, closing.
