### ISSUE TITLE
Packetdrill crashes when SND_BUFF < MSS

### ISSUE THREAD

**Issue by redward** [multipath-tcp/mptcp#50]
When the SND_BUFF is set less than the MSS and using tcp_cork, MPTCP is running forever and on the network it sends several times the same segment. 

Found with Packetdrill [tcp_cork_on_09.pkt](https://github.com/ArnaudSchils/packetdrill_mptcp/blob/master/gtests/net/packetdrill/examples/tests/tcp_headers/tcp_cork_on_09.pkt)

**Comment by cpaasch** [comment]
What happens is that the write()-call becomes blocking because there is not enough space in the send-buffer.

With regular TCP this does not happen, because TCP always allows to put at least one segment inside the send-queue. As TCP enforces GSO (you only disable TSO. GSO is the same as TSO except that it relies on OS-support instead of NIC-support), it will create one large GSO-segment that is able to contain the 9999 bytes you are sending.

With MPTCP, we disable GSO, because DSS-csum is enabled. Thus, the send-queue would need to hold more than 1 segment as no large GSO-segment can be created.

So, this is not really a bug. It's by design. You can try out by disabling dss-checksum if it then is not blocking anymore.
