### ISSUE TITLE
Finding out MPTCP version and missing scheduler?

### ISSUE THREAD

**Issue by mrconter1** [multipath-tcp/mptcp#507]
Hi,

I am running the following:

```
OS: Ubuntu 20.04.5 LTS
Kernel: 5.15.0-67-generic
```

Directly after installing the system I run `sudo sysctl -a | grep mptcp` which gives me:

```
net.ipv4.tcp_available_ulp = espintcp mptcp
net.mptcp.add_addr_timeout = 120
net.mptcp.allow_join_initial_addr_port = 1
net.mptcp.checksum_enabled = 0
net.mptcp.enabled = 1
net.mptcp.stale_loss_cnt = 4
```

So I guess Ubuntu 20.04.5 LTS kind-ish seems to ship with MPTCP. But I have two questions:

1. How can I find out the underlying MPTCP version that seems to come with this Ubuntu release? Running `dmesg | grep -i mptcp` will only give me:

```
[    0.654181] MPTCP token hash table entries: 8192 (order: 5, 196608 bytes, linear)
[    2.363938] systemd[1]: Set hostname to <mptcp-TUF>.
```

2. If I now have MPTCP, do I have any schedulers installed? It doesn't look like that? How would I install/enable them?

Best regards, Rasmus

**Comment by matttbe** [comment]
Hi,

> Kernel: 5.15.0-67-generic

It looks like you are using the new (re)implementation of MPTCP that is now in the upstream kernel (since v5.6).

This is different from the one tracked in this repo:
* https://github.com/multipath-tcp/mptcp_net-next/wiki#upstream-vs-out-of-tree-implementations
* https://www.mptcp.dev
* https://multipath-tcp.org
* https://github.com/multipath-tcp/mptcp_net-next

The work is still in progress. For the moment, there is only one scheduler and 2 path-managers (controlled from `ip mptcp`, `mptcpd` and newer versions of NetworkManager and others).

We do recommend using the last stable kernel, see the [ChangeLog](https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog).

I guess I can close this ticket. If you have problems with the new implementation, please open a new issue in [the other repo](https://github.com/multipath-tcp/mptcp_net-next).
