### ISSUE TITLE
MPTCP installed but amiusingmptcp.de is saying it is not

### ISSUE THREAD

**Issue by sanjitbarik** [multipath-tcp/mptcp#511]
It is a little modifed one, tomorrow I will test the pure code from your website.

You are absolutely right, I have checked the protocol in another network and "http://amiusingmptcp.de/" returning "Yes". 

I will find the middleboxes blocking the protocol.

Thank you so much for your time, patience, and detailed answers

_Originally posted by @rezapoorzare1 in https://github.com/multipath-tcp/mptcp/issues/484#issuecomment-1118698827_

**Comment by sanjitbarik** [comment]
Dear sir
I have a same same problem.Please inform what have done for solve the issue

**Comment by matttbe** [comment]
@sanjitbarik please explain your issue, I have no idea what's your issue.

**Comment by matttbe** [comment]
> I installed Ubuntu 20.04 and know I am in the kernel.There is problem : The command "sudo dmesg | grep MPTCP" returns: [ 0.372344] MPTCP: Stable release v0.95.2 sysctl net.mptcp.mptcp_enabled| returns: net.mptcp.mptcp_enabled = 1
> 
> "sysctl -w net.mptcp.mptcp_path_manager=fullmesh" returns: net.mptcp.mptcp_path_manager = fullmesh sysctl net.ipv4.tcp_congestion_control it returns cubic everything looks good, but when I connect to "http://amiusingmptcp.de/". it says no. Please give me solution thanks.

It is possible a middlebox somewhere between you and the server is blocking MPTCP. Most of the time, it is due to a wrong configuration somewhere, either on your side or on the operator' side.
You can use tcpdump to see if MPTCP packets are going out but if yes, you will need a tool like tracebox to identify where MPTCP options are stripped, see: https://multipath-tcp.org/pmwiki.php/Users/Tools (at the end)

```
docker run -it --rm matttbe/tracebox:latest -p 'IP/tcp{dst=443}/MPCAPABLE' www.multipath-tcp.org
```

**Comment by sanjitbarik** [comment]
Hi it works in different network. thanks
