### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by maojianyou** [multipath-tcp/mptcp#524]
[root@localhost opt]# rpm -ivh kernel-5.4.230.mptcp-13.x86_64.rpm 
error: Failed dependencies:
        rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by kernel-5.4.230.mptcp-13.x86_64

**Comment by maojianyou** [comment]
cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

**Comment by matttbe** [comment]
Hello,

`multipath-tcp/mptcp_net-next` repo is for the MPTCP support in the upstream Linux kernel, since kernels v5.6.

The RPM you are trying to use have been built on [Fedora 37](https://github.com/multipath-tcp/mptcp-scripts/commit/eddfc75a4db04237a5a855a8ae3234a68f91f400). Likely CentOS 7.9 is too old, you need at least CentOS 8 (or CentOS Stream which is ship with MPTCP support by default).

I guess we can close this issue. Feel free to re-open it if something is missing.
