### ISSUE TITLE
waring: frame size larger than 1024

### ISSUE THREAD

**Issue by hongweishang** [multipath-tcp/mptcp#72]
when i complie the mptcp, some warnings like "frame size xxx  larger than 1024". Doesn't it matter?

**Comment by sebstbarre** [comment]
I think it doesn't matter: This is actually not related to MPTCP as I see this warning as well in vanilla Linux v3.17. Note that it is still present even in v3.19-rc5.
GCC simply tells us here that some functions are a bit greedy in stack usage. This particular case however is only slightly above the threshold, and should not cause any problem (otherwise many people would have reacted already and the warning would not have survived two kernel releases)

**Comment by cpaasch** [comment]
Closing this issue as it's a non-issue :)
