### ISSUE TITLE
Strange restriction bandwidth

### ISSUE THREAD

**Issue by Kotische** [multipath-tcp/mptcp#73]
If I connect 2 servers:
4 ethernet direct to 4 ethernet by cables
I have about 4g bandwidth on 1 flow.

If I connect 2 servers:
4 ethernet to cisco catalist and then to 4 ethernet 
I have about 1.6 g bandwidth on 1 flow.
But I have about 4g total bandwidth on 4 parallel flow.

**Comment by Kotische** [comment]
But I have about 4g total bandwidth on 4 parallel flow.

**Comment by obonaventure** [comment]
Please ask the question on the mptcp-dev mailing list and provide a bit more information on the configuration of the catalyst switch. Do you use the same MTU in both cases?

**Comment by Kotische** [comment]
It is real bug!
linux distrib - debian swueeze
Mptcp version  - 0.88
net.mptcp.mptcp_path_manager = fullmesh

All eth adapter on some network.
This case generate interferente traffic.
As result total bandwidth too low.

I define  iptables rules one to one accept
and drop crossower traffic and bandwidth  now 3.82 g/s!

**Comment by cpaasch** [comment]
Yes, having the crossover traffic is bad for the bandwidth. As the number of subflows increases, the CPU-overhead increases and scheduling across the subflows also gets less optimal.

Ideally, you want to minimize the number of subflows. So that you have one subflow per bottleneck and only send one single subflow across each bottleneck.

Automatically preventing these crossover subflows within the kernel is quite a difficult problem. If you have an idea, that would be great! :)

**Comment by Kotische** [comment]
fullmesh manager does not allow to specify the number of subflow :(

ndiffports manager & num_subflows=4 does not show a positive result :(

it would be nice if there was a cache file showing the current state of the connection and default preset  for it.

for example:
node1 
ip1 192.168.1.1
ip2 192.168.1.2
ip3 192.168.1.3
ip4 192.168.1.4
subflow preset 4
subflow1 192.168.1.1 -192.168.1.100
subflow2 192.168.1.2 -192.168.1.101
subflow3 192.168.1.3 -192.168.1.102
subflow4 192.168.1.4 -192.168.1.103

**Comment by cpaasch** [comment]
Yes, a proper interface to specify which subflows should be created would be good. E.g., over netlink,...

Patches are very welcome! :)

(I think, we can close this issue-report and move discussion about an API for path-management to the mailing-list)
