### ISSUE TITLE
MPTCP kernell on openstack virtual machine

### ISSUE THREAD

**Issue by Raksus** [multipath-tcp/mptcp#96]
Hi, I'm trying to install mptcp kernel on ubuntu 15.10 virtual machine on openstack enviroment and I'm having the following error:
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-mptcp : Depends: linux-headers-3.18.20-90-mptcp but it is not installable
               Depends: linux-image-3.18.20-90-mptcp but it is not installable
E: Unable to correct problems, you have held broken packages.

I followed this guide: http://multipath-tcp.org/pmwiki.php/Users/AptRepository

**Comment by cpaasch** [comment]
@rbauduin: Can you take a look into this? Thanks!

**Comment by rbauduin** [comment]
I cannot reproduc the problem now, but note I updated the packages a couple of hours after you opened the issue. Can you try again to see if that update fixed your problem?

**Comment by GinesGarcia** [comment]
Hi, i'm having the same problem when i try to install mptcp kernel on ubuntu based virtual machine (openstack environment).

I tried to create an ubuntu image with mptcp kernel, clean the instance (using http://docs.openstack.org/image-guide/content/ubuntu-image.html in order to get an openstack-compatible qcow2 disk) but finally i couldn't build it as an image with glance image-create command.

thanks!

**Comment by rbauduin** [comment]
the v0.90 mptcp kernel from the trusty repo installs succesfully on ubuntu 15.10.  The problem with `glance image-create` seems unrelated to the linux-mptcp package. Don't hesitate to provide more info if you think otherwise.

**Comment by cpaasch** [comment]
Closing this one. Please reopen if necessary.
